version: "3.8"

services:
  discord-bot:
    build: .
    container_name: discord-qotd-bot
    volumes:
      - ~/Coding-Projects/Bot-FurlumbiansV2:/app
      - ~/Coding-Projects/Bot-FurlumbiansV2/config.json:/app/config.json
    restart: always